### ISSUE TITLE
Set up New Relic service

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1007]

**Comment by mogul** [comment]
The manifest option is only for when you're using the PHP buildpack. The Python integration is about like you described.

I'm working on getting the license key sorted out... TTS has group licensing and there's an internal process that I'm pursuing to get the FAC account set up.

**Comment by asteel-gsa** [comment]
> The manifest option is only for when you're using the PHP buildpack. The Python integration is about like you described.
> 
> I'm working on getting the license key sorted out... TTS has group licensing and there's an internal process that I'm pursuing to get the FAC account set up.

Gotcha, okay, so we will just leave it in backlog and plan for it when the license key and account is setup.

**Comment by mogul** [comment]
For Step 4 (actually 3), we provide the license key to the app via [a user-provided service](https://docs.cloudfoundry.org/devguide/services/user-provided.html).

For Step 3 (actually 4), we generate the config file before the start command is invoked by [calling the utility in the .profile file](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#profile).

**Comment by mogul** [comment]
Now blocked on New Relic license availability

**Comment by JeanMarie-TTS** [comment]
@asteel-gsa

**Comment by asteel-gsa** [comment]
Per @JeanMarie-TTS I have uploaded necessary files [here](https://github.com/GSA-TTS/FAC/tree/asteel/new-relic-poc)

I was unable to get `$NEW_RELIC_LICENSE_KEY` passed into the `.ini` on the `docker container` and as such, for now, has to be manually input [here for syslog](https://github.com/GSA-TTS/FAC/blob/asteel/new-relic-poc/backend/newrelic.conf) and [here for the license key](https://github.com/GSA-TTS/FAC/blob/asteel/new-relic-poc/backend/newrelic.ini)

In order to use the dashboard locally, [navigate here](https://newrelic.com/signup?via=login), create an account, grab your License Key, and replace it as necessary. Moving `NEW_RELIC_LICENSE_KEY` into `.env` and `docker-compose.yml` did not seem to work for me.

**Comment by mogul** [comment]
@asteel-gsa and I paired on setting up the cloud.gov side of things in #1077 and that should be good to go. Once that merges the agent will be shipping telemetry to NR from all of our spaces, which should be enough to have us ready for assessment. 

We may need additional PRs to [set things up for local development](https://github.com/GSA-TTS/FAC/commit/c725e847e01c02864eefcc6b0f7fe2e9acb550ca#diff-fed51f49a9f26cb93cc870efdc9419d425b9422354ae41bb651c3333c8bff486R50-R53), or to [customize settings applied per-space](https://github.com/GSA-TTS/FAC/commit/c725e847e01c02864eefcc6b0f7fe2e9acb550ca#diff-9b7ffee6814b70814ab29d34686e6793da2ccfa566554240885fa968391b81adR235-R254).

**Comment by mogul** [comment]
We've set up the agent but the license key we have isn't working. We've opened [a support case with New Relic](https://support.newrelic.com/s/case/5008W000015VYTl).

**Comment by asteel-gsa** [comment]
With [this PR](https://github.com/GSA-TTS/FAC/pull/1132) the service 'gsa-fac' is now visible in new relic

![image](https://github.com/GSA-TTS/FAC/assets/130377221/88b9b068-fc65-457e-aa5d-69dc76b023fe)
![image](https://github.com/GSA-TTS/FAC/assets/130377221/959ba424-f396-47be-8b57-50d4dc9aebad)
