### ISSUE TITLE
FAC - Bug: Cluster Name column in federal-awards-expended-template xlsx is lacking the list of cluster names

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#1227]
### Describe the bug

The federal-awards-expended-template xlsx is lacking the list of valid names in the Cluster Name column. In order for users to enter the correct name when filling out this file, it is necessary to attach a list of valid cluster names to the respective cells in this column. However, the list is currently missing due to the limitation of Excel's formula string length, which is restricted to 255 characters. 

### Steps to reproduce the bug

1. Go to the XLSX template [repo](https://github.com/GSA-TTS/FAC/tree/main/backend/schemas/output/excel/xlsx) and download [federal-awards-expended-template.xlsx](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/output/excel/xlsx/federal-awards-expended-template.xlsx).
2. Open the file and notice that cells in Federal program name column do not have a list of names attached.

### Expected Behavior

When entering data in the Cluster Name column of federal-awards-expended-template.xlsx, users should be able to select an option from a list of valid name. 
As a solution, the XLSX template generation script needs to be modified specifically for this case. The modification will involve generating the list of valid names in a hidden sheet and associating each cell in the Cluster Name column with the corresponding names from the hidden sheet.

### Screenshots

![image](https://github.com/GSA-TTS/FAC/assets/26260777/2e0773a4-6590-4942-a54c-95031581f52d)

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
This will get picked up in another PR, which currently has linting errors. 

Well, most of it will. We now have the ability to drop sheets in with text columns, so that we can put our enumerates into the workbooks. These can then be used to populate/validate the name columns.

I also pulled some current data from Census and automated its transformation from CSV to JSON, so we can include it directly into the Jsonnet build process. I'm pretty sure I have Makefile changes in that PR that incorporate this.

We'll update/comment further on this ticket once we see where that PR takes us. The optionality of the program name (for example) is not part of the other PR.

**Comment by sambodeme** [comment]
As part of PR #1345, the cluster names list was added to federal-awards-expended-template.xlsx, resulting in the resolution of this issue.
