### ISSUE TITLE
Create a new audit submission based on valid entity data

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#126]
## Background
When users are creating a new audit, they are guided to enter an ID number (likely the [UEI](https://sam.gov/content/entity-registration), sam.gov, pending PDR in #120) that is then checked against a database. They need to see what is returned from that database and confirm that it is the correct entity for which they want to create a new submission. 

(The UEI being the ID in question is dependent on #120 being decided.)

## It covers following stories...

4. As an auditee or auditor creating a new audit, I need to choose my entity among a list of possible entities that may come up when I search by identifier so that I can create a new submission for my entity. (This continues the list of stories in #104; see that issue for context.)

## We'll know we're done when...(aka acceptance criteria)
- [x] When a user can have an entity name (or list of names) returned after they enter a UEI
- [x] When a user can choose the entity name they'd like to proceed with 
- [x] The entity name they've chosen is pre-populated in the name field
  
### Design Tasks - Austin
- [x] ~https://github.com/GSA-TTS/FAC/issues/166~ Deprecated 
- [x] https://github.com/GSA-TTS/FAC/issues/165 

### Product Tasks - Peter
- [x] https://github.com/GSA-TTS/FAC/issues/167

### Engineering Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/170 
- [x] https://github.com/GSA-TTS/FAC/issues/169 
- [x] https://github.com/GSA-TTS/FAC/issues/164 

## Definition of Done
- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by Jkrzy** [comment]
Checking my understanding since this was written a few weeks ago....

* UEI's are associated with single entities
* Users must provide a [valid](#104 ) UEI to proceed
* For a given UEI, we'll never be able return more than a single associated Entity name from sam.gov
* Users won't be able to edit data fields returned by sam.gov

If ☝️ is true, the only user modifiable input on this page _should_ be the UEI field?

cc: @jadudm, @MelissaBraxton

**Comment by jadudm** [comment]
This feels correct, @Jkrzy. 

Also, see #153. It suggests that the entity type is also encoded in the SAM.gov data, which is interesting. (Because we ask the user for entity type, but technically, we should be able to get valid entity type from sam.gov?)

And, yes. We have to have the UEI. A question I have is (two, perhaps?):

1. Can someone "skip" this page and do it later, but they can't complete the submission as a whole (and probably can't certify) until there's a valid UEI?, OR
2. Do we require it at "this step," and prevent them from going forward without it?

That is, do we allow them to partially complete the form out-of-order, or is there strict sequencing?

**Comment by petermarks-gsa** [comment]
I attempted to break up this story into sub tasks to make it more actionable and achievable. Here’s my thinking behind this approach: 

- Clarify exactly who from design and engineering is accountable for each part. Previously only Austin was assigned this ticket when it has engineering parts. 
- Encourage discussion and clarification of each individual piece in their own ticket. Threads at the story level can get pretty intense, especially if there’s a lot of back and forth in requirements gathering and QA. 
- Add a “story” label to this to communicate that it’s a team-wide issue, not a discrete piece of design or engineering work that can be picked up by one person. 

This is my first time breaking up a github story into assignable tasks, so certainly open to feedback! Just trying to model something I’ve seen work well in the past :)

**Comment by MelissaBraxton** [comment]
Added note to reflect that #166 is closed/deprecated.

**Comment by MelissaBraxton** [comment]
## If format error:
We don’t recognize the UEI you entered. The UEI should be 12 characters and a combination of letters and numbers.

## If API is working, but UEI isn’t recognized:
We don’t recognize this UEI. You can continue for now, but you’ll need to come back to this. [Find out how to get a UEI](#).

## If API isn’t working:
We can’t connect to SAM.gov to confirm your UEI. We're sorry for the delay. You can continue, but we'll need to confirm your UEI before your audit can be certified.

**Comment by heymatthenry** [comment]
@MelissaBraxton The server is responsible for looking up & validating the UEI, so the first two error messages need to be implemented on the server-side and returned to the front-end via the API (cc: @Jkrzy @geekygirlsarah). I'll implement the last one on the front-end now and tack it onto #170.

**Comment by heymatthenry** [comment]
To be clear, the part where the server does those validations and returns an error message that the front-end displays is all implemented already—all this requires is a change to the text.
