### ISSUE TITLE
Change `report_id` to eliminate randomness

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1261]
As per [today’s dev huddle](https://docs.google.com/document/d/1LoHhx0dxS3wCvSSKE_d033b5RcN_PLKVFjkkrLzUnMg/edit#heading=h.5akqo0udz87w), we want to remove the random portion of `report_id` and replace it with an all-caps three-letter abbreviation for the month in which the submission was created. 

The current method for creating `report_id` is in `SingleAuditChecklistManager`:

>    A 17-character value consisting of:
>        -   Four-digit year of start of audit period.
>        -   Three-digit char (but without I or O) random.
>        -   10-digit numeric monotonically increasing, but starting from
>            0001000001 because the Census numbers are six-digit values. The
>            formula for creating this is basically "how many non-legacy
>            entries there are in the system plus one plus 1,000,000".

This ticket is to track replacing “three-digit char (but without I or O) random” with “three-character ISO month abbreviation”.

**Comment by tadhg-ohiggins** [comment]
Addressed by #1262

**Comment by mogul** [comment]
@Carley-Sullivan what's the most logical date that should be used as the basis for picking the month? We are using the month the submission was created but we could derive it from one of the other dates collected...

**Comment by mogul** [comment]
How it looks now...
![image](https://github.com/GSA-TTS/FAC/assets/47762/0ab56675-b4e9-4a39-982b-52f190df5d74)

**Comment by Carley-Sullivan** [comment]
@mogul Month submission was created is fine.

**Comment by tadhg-ohiggins** [comment]
At the moment we're using year and month of the start of the audit fiscal period.

**Comment by Carley-Sullivan** [comment]
Using the Fiscal Period start date YYYYMON is fine.  Are the last 10 digits of the Report ID unique per submission in order to prevent duplicates?

**Comment by jadudm** [comment]
Yes; the last 10 digits are a global counter. Using "counting numbers," this gives us around 10B submissions to work with. 

Note: we don't have a way, I think, to reuse indexes. Put another way:

1. We assign an id at the *start* of the submission. 
2. The submission may, or may not, be completed.

Granted, we have no way (yet) for canceling a submission once started. But, the fact that we assign the ID at the start of the process means that we may end up with gaps in the counter, and for all I know, every submission may have 5 or 10 failed starts, suggesting that we have 1B instead of 10B indicies to work with.

Regardless, this format gives us plenty of runway.
