### ISSUE TITLE
Data type issues in v1.0.0-beta

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1548]
From our Federal partners:

1. Fields that are “integer” and should be “character varying”
     1. `auditee_ein` on all tables 
     2. `general.auditee_addl_ein_list`
     3. `general.auditor_ein and auditor.auditor_ein`
     4. `general.oversight_agency`
2. `general.auditee_duns` is currently “character varying[]”, but I assume it should no longer be an array with the addition of `general.auditee_addl_duns_list`

For us, internally:

Given concerns with silent truncation and uncertainty about data coming from Census, we're modeling all `character varying` fields as `TEXT`, all integer fields as `NUMERIC`, and all date fields as `DATE`. We will need to check, when we begin historic ETL, that the date formats stored by Census/Oracle are compatible with GSA/Postgres.

**Comment by jadudm** [comment]
An initial design thought:

There are historical columns that only exist in the Census data, and sometimes only in *old* Census data. We would like to not burden the API and the new model with those columns.

We suggest adding `/historic/general` or similar to the API. This "historic general" table would contain those columns that are "legacy." We would key the rows with the `report_id`, and if the source is `Census`, you could then reach into the historical table and grab the additional/historic fields. 

However, there is no reason for us to carry them in the 2023 collection, because (for example) we do not collect the DUNS number, and will (hopefully) never again.

**Comment by jadudm** [comment]
Not noted from conversation: thank you! Yes, we'll correct these data types.

**Comment by JeanMarie-TTS** [comment]
@jadud, here's what I plan to implement. Please let me know if you think something needsto be done differently:

- [ ] Implement a table for additional eins, like we have for additional uei
- [ ] Use a boolean field to indicate the presence of additional info like additional UEI. Use a naming convention to identify these boolean fields.
- [ ] Use BigInteger instead of Decimal for amount fields
- [ ] Use Textfield for character fields except when the length is known 
- [ ] Exclude hist_ fields from the view definition. This will include explictly specifying column names instead of using wildcards.

**Comment by jadudm** [comment]
`ein` is a text field everywhere in our dissemination.

`oversight_agency` is a text field.

`duns` is moving to a historical view, and will come back when we have historical data with that field.

`additional_eins` as an endpoint is currently missing, and will be added in. This will break out in the same manner as `secondary_auditors`. 

Leaving this open until that work is complete.
