### ISSUE TITLE
Auditee certification is a source of truth

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1568]
```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
- [x] Content signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy, same as with Auditor certification, I've combined these into one screen. We can go over together next week.

**Comment by lauraherring** [comment]
@jadudm @thebestsophist @James-Paul-Mason @Carley-Sullivan 

@Leighdiddy and I are good to go on the content and design for auditee certification. We both prefer the combined page but understand if the devs can't pull that off at this point in time. The broken-out version is fine, too

@Carley-Sullivan I did changed the checklist back to the copy from the purple form, with the exception of subbing "workbooks" for "SF-SAC" since we no longer have anything we call "SF-SAC" and I didn't want to confuse anyone.
