### ISSUE TITLE
The timestamps are wonky. They should be fixed.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1637]
Long-and-short is that timestamps, as presented to the user, do not reflect their timezone. Although our storage in UTC is appropriate, it makes no sense to a user to see a timestamp in their future.

When presenting timestamps to the user, they should see a value that makes sense given their current, lived experience.

**Comment by JeanMarie-TTS** [comment]
@jadudm Please provide more details one what the problem is and what is required.

**Comment by timoballard** [comment]
@jadudm 

Background: Django stores all timestamps in UTC in the database. When rendered in templates/forms, these timestamps will be converted to the active timezone. The default active timezone is specified by `settings.TIME_ZONE` (currently set to "UTC", which is why we're seeing UTC timestamps on the frontend).

Django has no builtin mechanism for automatically determining a user's time zone, so our options are (some combination of):
- Allow the user to set their time zone from the front end, which we store in their `user_profile`, and we add request middleware to set the active timezone according to what is stored in their `user_profile`
- Investigate django packages (like [this](https://github.com/Miserlou/django-easy-timezones), or [this](https://github.com/adamcharnock/django-tz-detect)) that try to determine a user's timezone automatically
- For now, just set the default (`settings.TIME_ZONE`) to something more reasonable, like "EST"

**Comment by jadudm** [comment]
If we use something automatic, do we run a risk of it being "wrong?" 

If we pick EST, we need to modify the views so they say "3:23 PM EST." We could do that.

We could also present upload timestamps as relative time: "Uploaded 33 minutes ago," "Uploaded about 3 hours ago," "Uploaded 4 days ago."  This would be robust against timezones. That might be fraught/more work than we want, but it would eliminate the whole timezone issue.

Any prefs from your point of view?
