### ISSUE TITLE
Implement Cognizant and Oversight assignment function without 2019 data

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#1699]
Breaking this out from its parent epic. See https://github.com/GSA-TTS/FAC/issues/1218 for more discussion and history.

This covers the implementation for cognizant and oversight assignment without 2019 data.

**Comment by gsa-suk** [comment]
Plan:
Implement the logic in a function cog_over_assignment in cog_over.py.
Call cog_over_assignment in backend->audit->views.py->_save_audit_data right before sac.save().

**Comment by JeanMarie-TTS** [comment]
@Carley-Sullivan 
Should we not check for Cog Agency assignment in 2019 before trying to determine a new one? If an auditee was assigned a Cog agency in 2019 but does not meet the threshold in 2021 will there be a Cog Agenct in 2021? If this same auditee then meets the threshold in 2022, will a new Cog agency be determined or will the one from 2019 be used?

@jadud
1. To look back at a 2018 submission to see who was the assigned cog agency, we need to map the auditee's current uei to their 2019 identifier, which could have been a duns or eon. How do we do this?
2. Can we afford to wait till history data is migrated for 2019 into our dissemination models, before we assign Cog agency based on 2019 submission? We sould do a one time re-assignment based on 2019 for the ones that need such an update. If not, we need to work on a special temporary migration of submissions with a cog agency assignment in 2019.

**Comment by Carley-Sullivan** [comment]
The assignment always needs to take into account the current year submission.  JM, I want to make a modification to your example because a 2019 submission would look back at 2014 for the base year.  

New example:

 A 2020 submission for an entity comes in with greater than $50M in expenditure. We will look at the 2019 base year Direct Award expenditure to determine Cog

Now let's say the next year they submit their 2021 and fall below the $50M expenditure. We will assign the Oversight agency - which is calculated on the current submission Direct Award expenditure.

 The following year they submit a 2022 submission that is above $50M. We run it through the Cog assignment process looking at 2019 base year.

**Comment by gsa-suk** [comment]
@Carley-Sullivan 
1. The base year for now is 2019.  In the 2019 historical data, the General table would already have the COG_OVER, COGAGENCY, OVERAGENCY data available.  Do we just use that data instead of doing calculations again?
2. For a submission in 2025, is the base year 2024 and so on?

@JeanMarie-TTS 
In the current dissemination model, there is cognizant_agency and oversight_agency in General.
