### ISSUE TITLE
Proxied connection from Cloud.gov to SAM.gov API

### ISSUE THREAD

**Issue by neilmb** [GSA-TTS/FAC#1701]
FAC needs to connect from a running Cloud.gov application through an egress proxy to the SAM.gov API. In the absence of the egress proxy, we closed our issue https://github.com/GSA-TTS/FAC/pull/1652 by specifying a custom SSL context that accepts the "legacy renegotiation" that the SAM.gov server is using https://github.com/GSA-TTS/FAC/pull/1652. (More context on the issue here https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled, e.g. "it happens when the server doesn't support RFC 5746 secure renegotiation and the client is using OpenSSL 3, which enforces that standard by default").

When using an egress proxy, we need to convince the SSL client *on the proxy* to accept the unsafe connection that SAM.gov is offering. Just using our previous fix doesn't fix this because the SSL connection from our application to the proxy works fine, the issue is with the unsafe behavior on the connection from the proxy to SAM.gov. (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2009-3555 and https://blog.qualys.com/product-tech/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix-2 for more info.)

Possible solutions include:

- SAM.gov updates their server to offer secure renegotiation as required by default on the modern versions of OpenSSL that we use.
- We figure out how to reconfigure the proxy running on Cloud.gov's `binary-buildpack` to specify the "unsafe legacy renegotiation" flag for its outgoing SSL connections (ideally only on connections to SAM.gov).
- We construct an entirely new service to provide UEI lookups without depending on SAM.gov, likely by downloading their database and building a service to make it available on an API (Postgrest?)

**Comment by mogul** [comment]
> When using an egress proxy, we need to convince the SSL client _on the proxy_ to accept the unsafe connection that SAM.gov is offering. Just using our previous fix doesn't fix this because the SSL connection from our application to the proxy works fine, the issue is with the unsafe behavior on the connection from the proxy to SAM.gov. (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2009-3555 and https://blog.qualys.com/product-tech/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix-2 for more info.)

Following up: This was a red herring... The CONNECT proxy protocol does not MITM SSL connections between the client and the server. 

The actual problem was that our use of a custom connection handler to work around the upstream legacy negotiation failing bypassed the proxy settings normally in use. In the `staging` environment, this meant the outbound connection was blocked by lack of egress. (We have verified this by removing `public_networks_egress` from the `dev` environment and confirming the same failure to connect to SAM.gov there.) 

We are now rolling out [a PR that makes use of the proxy in the custom connection handler](https://github.com/GSA-TTS/FAC/pull/1708) which we believe will fix this.

**Comment by tadhg-ohiggins** [comment]
Seems to be working everywhere that I know of, so yes!
