### ISSUE TITLE
Questions on fields: total_fed_expenditures, type_report_major_program, type_requirement

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1734]
## Questions (to answer below)

1. Where does `total_fed_expenditures` come from?
2. Where does `type_report_major_program` come from?
3. Where does `type_requirement` come from?

Correct answers might be 

1. Where they come from
2. They're not needed, because they were last collected in 1327
3. ...

We just don't know if they're something we're missing (and need), or something missing that we *don't* need...

**Comment by Carley-Sullivan** [comment]
total_fed_expenditures is the system generated summation of all federal award expenditures (AMOUNT in the CFDA file).  At Census, it was located on the Federal Awards workbook. This field is a MUST.  It is required in order to determine Cognizant/Oversight assignments.

type_report_major_program ...could you mean TYPEREPORT_MP? I don't think I've ever used the label type_report_major_program it has always been TYPEREPORT_MP for me.  Its likely an historical name but pointing to the same thing. If you're capturing TYPEREPORT_MP then we are covered.

type_requirement is on the form at III/4/f "Type(s) of Compliance Requirement(s).  This must be in the findings workbook.

**Comment by JeanMarie-TTS** [comment]
@jadudm, @sambodeme, @pluribus-tony   It looks like we do compute `total_amount_expended` , but we store in a different place. It's currently being stored in the JSON for FederalAward in the header. 
Our dissenination model does not have a separate table to store a field from the header, but we could choose to store it on every award line. Another option is to store it in SAC as a field and in the General table in the dissemination model.
Thoughts and suggestions?

**Comment by JeanMarie-TTS** [comment]
@pluribus-tony We have `mp_audit_report_type` in FederalAward. So, we don't need `type_report_major_program` in General. In addition the field `is_major` in FederalAward is redundant as it is a boolean which says whether or not `mp_audit_report_type` is null

**Comment by JeanMarie-TTS** [comment]
@pluribus-tony 
`type_requirement` is present in Finding and can be removed from FederalAward

**Comment by JeanMarie-TTS** [comment]
Fixed in #1786
