### ISSUE TITLE
Fold `report_submission` app into `audit`

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1847]
We currently have two apps:

* `report_submission`
* `audit`

The general info form lives in one, and the rest of the submission in the other.

In the name of code cleanup, we should bring the forms/tests/work from `report_submission` into `audit`, and shutter the `report_submission` app.

Before moving this to available, this ticket needs a tasklist expansion capturing the work steps that requires. For example, there will be some code in `settings.py` that should be removed (e.g. an app), but also we need a rough map for what tests, etc. need to come over.

**Comment by tadhg-ohiggins** [comment]
Because this includes public URLs that will be live post-launch, we'll have to support those URLs in future whenever we do this. In other words, the easy path of just moving things to the `audit` directory in the application isn't available and we'll have to make sure to add redirect rules to cover the old URL paths.
