### ISSUE TITLE
ADR for how we are enabling bulk data upload

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#186]
**Background**
Much of the design and dev work on the AF-SAC form data entry is dependent on us having a clear sense of how we are enabling users to bulk upload data. We need to decide how we will do this in order to unblock the rest of SF-SAC form data entry work. 

**We'll know we're done when...**
- [ ] We've reviewed [Matt's spike](https://github.com/GSA-TTS/FAC-xlsx-validator) and evaluated whether electron is the right direction
- [ ] We have an approved ADR that records our decision on how we are doing bulk data upload for SF-SAC form data. 

Not necessarily in scope for this ADR, but something to consider
- [ ] Saving the PDF

**Comment by jadudm** [comment]
For clarity:

1. Electron is secondary to the ADR. I think we just need to decide/document that we are committed to consuming XLSX templates. The Electron piece is a red herring, because it suggests a desktop application. I would make that a separate ADR. 
2. The second question, in terms of schema, should instead be "are we using SheetJS Community Edition" as our library for parsing and processing our templates. 

https://www.npmjs.com/package/xlsx

That's a link to the package on `npm`. The spreadsheet JSON object produced by that library is documented as the "Common Spreadsheet Format":

https://www.npmjs.com/package/xlsx#common-spreadsheet-format

Granted, that might mean "this library defines the CSF," but... the important thing is that the library produces a well-documented, widely used JSON structure. 

So, instead of saying we'll define a schema (which I think has very specific meaning), I think we say "we'll use the Common Spreadsheet Format JSON object produced by SheetJS." 

Later, we could have an ADR that defines a subset of this, but for now, this would simplify the ADR to answering three things:

1. Are we committed to ingesting a set of templates that are closely modeled on the existing templates provided by Census, 
2. Are we using SheetJS as our parsing library, and
3. Are we using the CSF as defined by the SheetJS Community Edition as our spreadsheet representation.

Which, assuming (from our conversation) that the answer to every one of those questions is "yes," the ADR itself becomes a declaration of those facts.

It also means we can begin breaking out some tickets for the backend to begin developing the API-side of the work independent of the front-end, because we know *exactly* what the JSON object will look like coming in, and we can build/unit test against that.

**Comment by MelissaBraxton** [comment]
This sounds great to me! With this added clarification, I think this is really close to done.  @geekygirlsarah, since I know this is your first ADR, I think all that needs to happen is  declaring that we will:

- Commit to ingesting a set of templates that are closely modeled on the existing templates provided by Census,
- Use SheetJS as our parsing library, and
- Use the CSF as defined by the SheetJS Community Edition as our spreadsheet representation.

Does this sound right? @petermarks-gsa, @jadudm, @tadhg-ohiggins, @Jkrzy 

Who is the final reviewer of this ADR?

**Comment by geekygirlsarah** [comment]
I read over this issue, reviewed [FAC-xlsx-validator](https://github.com/GSA-TTS/FAC-xlsx-validator), and reviewed the npm libraries the app uses. After this, I think we can declare:
* We can commit to ingesting a set of Excel templates similar to the current existing ones at Census
* Use SheetJS as a parsing library
* Use the [Common Spreadsheet Format](https://github.com/sheetjs/sheetjs#common-spreadsheet-format) (CSF) for representing the data

(I don't know that right now I'd recommend Electron for building this, though I do think a static page on the site can use the libraries to do the same work. I think this thought is outside of scope of this ticket though.)

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Tagging you to review

**Comment by petermarks-gsa** [comment]
@geekygirlsarah Next step is to formalize this in a md file and PR into https://github.com/GSA-TTS/FAC/tree/main/docs/architecture/decisions
