### ISSUE TITLE
FAC - Bug: when uploading corrected workbooks, file must be renamed in order to upload 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1944]
### Describe the bug

Open test user feedback, when uploading corrected workbooks the file must be renamed in order to upload. See user note for explanation: 
<img width="720" alt="Screenshot 2023-08-24 at 5 13 26 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/69b606fb-4181-4d18-9f04-5c80920b314a">

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
The naming issue sounds like the widget not refreshing. I suspect this is a front-end, not a backend issue w.r.t. the reupload. 

The... one-at-a-time question is one that I'd like to explore, because I don't actually think it is true. However, I have no idea what errors the user was facing, and whether it is, or is not true in that case. But, we can look into this.

**Comment by jadudm** [comment]
See also: https://github.com/GSA-TTS/FAC/issues/2017

**Comment by jadudm** [comment]
Not strictly true. However, it doesn't trigger nicely. Leaving this for a moment, because it is a nice-to-have interaction bug, but not a show-stopper for submission.
