### ISSUE TITLE
FAC - Bug: PDF upload page missing required step

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2002]
### Describe the bug

open test user feedback: 
_When inputting page #'s for the report, for the Summary Schedule of Prior Audit Findings 2 CFR 200.Sll(b), it indicates if no findings this can be omitted, but this should be included even if there are no findings, as it is a component of the reporting package._

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by tadhg-ohiggins** [comment]
Here's what I think this means:

We indicate that the page number for prior audit findings is an optional field on `/audit/upload-report`:
![image](https://github.com/GSA-TTS/FAC/assets/2626258/de861103-8c80-4473-b2e9-03b0b6f09b62)

The user here seems to be suggesting that this should not be optional, because they think (maybe correctly) that the PDF must contain something stating the number of findings, even if that number is zero, and therefore that our form of relevant page numbers should require the number of that page regardless of the number of findings.

Are they correct, and do we want to make this field required, and did Census require it (and if not, why not), and are there any PRA implications here?

**Comment by danswick** [comment]
As far as I know, page numbers have always been a purely internal thing for Census staff and I'm going to close as unplanned. If there's a more urgent need to mark these as required, we can always reopen.
