### ISSUE TITLE
[HD]: Can't upload Federal Awards Audit Findings Workbook

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2545]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/388

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/u/2/folders/1Qgc4hctP4tKdVZCxV3KqvXeAlrgI89Ny

### What happened?

User tried all of the current fixes, still no luck.

**Comment by danswick** [comment]
The issue is in column `K`: **2022-001 AND 2021-001**

The only real guidance we give is in the column header: _If Repeat Finding, provide Prior Year Audit Finding Reference Number(s)_. However, the validation is [strict](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/base/Base.libsonnet#L291) and requires the reference numbers to be comma-separated.

We should do a couple of things:
* Update the instructions here: https://www.fac.gov/resources/workbooks/federal-awards-audit-findings/
* Add a set of new-style validations for the findings workbook. Findings errors are vague or non-existent now because of the old Jsonnet nested-logic problems we were running into with Awards.

**Comment by tadhg-ohiggins** [comment]
Note that the new validation reports an error but displays a blank table. The logs show this message:

```
No named range matches this error path: deque(['FindingsUniformGuidance', 'findings_uniform_guidance_entries', 0, 'findings'])
```

**Comment by tadhg-ohiggins** [comment]
Pretty sure this was fixed a while back.
