### ISSUE TITLE
Clone, clean and test workbook generator

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2576]

**Comment by phildominguez-gsa** [comment]
@JeanMarie-TTS We've made a PR [here](https://github.com/GSA-TTS/FAC/pull/2627). At this point we've copied it into `/c2g` and moved most of the logic into a `workbook_generator` module. We initially considered making a WorkbookGenerator class, but decided it's not really needed at this point (or maybe ever?). We generally left the methods as-is instead of trying to optimize and whatnot, but we can look into that in follow-up PRs. Probably can improve some of the comments/docstrings as well. Let us know your thoughts.
