### ISSUE TITLE
Boolean fields for API

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2597]
We are missing two (three?) more fields:

* `is_multiple_eins`, which is captured from the general form
* `is_secondary_auditors`, which also is a boolean checkbox on the general form

The data dictionary suggests we already have `is_multiple_ueis`. We need the other booleans to be complete in terms of disseminating what we collect.

**Comment by phildominguez-gsa** [comment]
- `is_multiple_eins`: I'm seeing `multiple_eins_covered` collected [in the general form](https://github.com/GSA-TTS/FAC/blob/main/backend/report_submission/templates/report_submission/gen-form.html#L173). We could add a new column to General and populate it via SAC, so [here](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intake_to_dissemination.py#L272) its value would be `general_information.multiple_eins_covered`. Alternatively, maybe we could do a query on the `AdditionalEin` table to populate true/false in the General view?
- `is_secondary_auditors`: `secondary_auditors_exist` is collected [in the general form](https://github.com/GSA-TTS/FAC/blob/main/backend/report_submission/templates/report_submission/gen-form.html#L486). Our options would be similar to `multiple_eins_covered`.
- `is_multiple_ueis`: This exists as `General.is_additional_ueis` [here](https://github.com/GSA-TTS/FAC/blob/main/backend/dissemination/models.py#L277), but I'm not seeing it in the views, so that can be easily added.

**Comment by purvinptl** [comment]
`“is_additional_ueis”: ”Yes”,` 
 `“is_multiple_eins” : true,` 
 `“is_secondary_auditors” : true`

This is a sample get request from postman. The `is_additional_ueis` is returning Yes but the others are returning true or false. Should we keep it or make the changes so it matches?

**Comment by jadudm** [comment]
Lets make it match. The reason is that the user checks a box at the front that says "Yes" or "No." So, we're trying to hold to a principle of disseminating what the user said/did. 

(Or: the philosophical question of whether or not *yes* is the same as *true* is not something we're prepared to answer.)

**Comment by jadudm** [comment]
Done with the merge of 1.0.3 fixes.
