### ISSUE TITLE
App HTML to match static site - search

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2732]
### Tasks

```[tasklist]
- [ ] The landing page for the app should match the static site, so we can get to search
- [ ] The nav wants to match, too.
```

No idea how to make this easier. :/  For now, we just have to remember to do it when we update one or the other.

**Comment by heymatthenry** [comment]
Other than text changes (App doesn't have the text "For more information on the features and development of the new FAC, check out our Updates page"), and inconsistent whitespace, the pages look the same to me. And both the static site and the app have links to search. What am I missing?

There are a couple of differences in the nav links which of course we can make consistent. The biggest difference is the search.gov box. I'm assuming that's still a static-only thing?

Another question is whether we should make any changes to the static site nav at the same time. We need to do something, since it's all smooshed now, so this might be a good time to come up with a solution to that. Thoughts, @Leighdiddy?

**Comment by lauraherring** [comment]
@heymatthenry I think the biggest missing thing now is that fac.gov has [the Search Resources page](https://www.fac.gov/data/resources/) under "Data" but the app side does not. But otherwise you're right, the top nav is aligned.
