### ISSUE TITLE
Front end - Audit report start page

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#279]
Dependent on user research: https://github.com/GSA-TTS/FAC/issues/293

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Feels like we've made a tentative decision in the [roadmap](https://github.com/GSA-TTS/FAC/pull/287) to replace in-app "certification" with signatures on pdfs, but that we'll validate that with user research? When do you think we'll have that research done by? Depending on when, it may or may not be worth starting this beforehand?

**Comment by MelissaBraxton** [comment]
I created this stub of an issue to track that research spike. #293 we'll need to prioritize it alongside other design work, but as long as we're ok to needing to revisit the "certify" CTAs on this page, I'd say we can proceed with the audit start page. I'd recommend completing this research in sprint 8 so that we don't end up blocking the design and implementation of the "certify" functionality, should we decide we need it.
