### ISSUE TITLE
Create model for saving information about census submissions that fail during migration

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#2815]
When a Census audit submission fails to migrate to GSAFAC, we want to save the DBKEY, AUDITYEAR, EIN, UEI, list of errors in a census_historic_migration_failed_sacs table for future analysis / transformations.  
The census_historic_migration_failed_sacs table will be saved in census-to-gsafac-db.

**Comment by jadudm** [comment]
It would be nice to see an ADR around this. We can chat a bit tomorrow.

**Comment by JeanMarie-TTS** [comment]
@gsa-suk We need to record the run_datetime so we know when this error occurred.
When we do a re-run and if a submission fails again, will we append another row? I think we should.

**Comment by gsa-suk** [comment]
@JeanMarie-TTS  Adding a row for each run will definitely provide clarity.

**Comment by gsa-suk** [comment]
When we pick a submission from this census_historic_migration_failed_sacs table, do necessary transformations and succeed, do we delete the submission from census_historic_migration_failed_sacs table ?

**Comment by JeanMarie-TTS** [comment]
1. In which app should we have these models? audit, dissemination, or census_to_gsafac? 
2. Can we design the table such that each error is a row? Can we have a way to determine how many submissions failed because of a particular type of error?
3. Can we have each error include the section in which it occurs?
