### ISSUE TITLE
Break `audit` out of monolithic files

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2828]
The approach of putting all views and models into single files isn’t suitable for projects beyond a complexity threshold that this project has clearly exceeded. We should move away from this approach. For `audit`:

```[tasklist]
- [x]   Move `models.py` to `models/` and put any new models into their own files.
- [ ]   Incrementally move models out of `models/models.py` into individual files.
- [ ] https://github.com/GSA-TTS/FAC/issues/2830
- [ ]   Move tests out of monoliths like `test_views.py` into their own files.
```

**Comment by jadudm** [comment]
Closing this out, as it has become part of ongoing work that we break up large files into subparts. The team has been doing this in a number of places. Although there may be more work, it is work that needs to be done _everywhere_, and we are doing it, as the opportunities present themselves. Closing as "done," in as much as this initial work happened, and it has happened elsewhere since November.
