### ISSUE TITLE
Handle unexpected and/or hidden named ranges in uploaded workbooks 

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2898]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/666

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/u/2/folders/1DSh2ksXtuXA-DfGDC83pPabJwKl-iCFb

### What happened?

User has been trying to upload workbooks since October. From user:

Update: I still cannot upload a workbook. I’ve done extensive testing with other staff in my office and in other Eide Bailly offices. Some can upload. Some cannot upload. I have been able to upload only one workbook to a test client, but the workbook had to be downloaded and filled out by another staff member. That is the only workbook I’ve been able to upload. None of the workbook templates I download and fill out are able to be uploaded by me or other staff. I wonder what is it with my account that your system doesn’t like.

**Comment by danswick** [comment]
This looks suspiciously like an issue with this individual's network and/or browser. @James-Paul-Mason, it could be worth finding out:

* To determine whether it's a network issue: has this person tried uploading while connected to a different network?
* To determine whether it's a browser issue: have they tried uploading from an incognito window? Do they have any browser extensions installed that could be interfering with the upload request? If possible, it could be good to test in a different browser, especially one that doesn't have any extensions installed. 

Happy to talk more about this if needed!

**Comment by James-Paul-Mason** [comment]
@danswick Thanks for the info!

**Comment by danswick** [comment]
Update from some further digging: 

This workbook has a bunch of hidden named ranges (screenshot below). I wasn't even aware that a workbook _could have_ hidden named ranges, but excel is nothing if not a reliable source of surprises.

These unexpected named ranges (`IQ_blah`) probably made it in via copy-paste from another workbook. Since we can't control copy-paste in the templates, we should filter out unexpected named ranges or only look for a predefined set, ignoring any others. I've renamed this ticket so we can use it to track that work. 

![image](https://github.com/GSA-TTS/FAC/assets/2365503/c755cea6-6289-4bf9-9fae-b769e901a6a9)

**Comment by James-Paul-Mason** [comment]
@danswick Great detective work, Dan! In the meantime should I communicate anything to the user about how she can correct her workbook, or are we focusing on fixing the bug so that her existing workbooks can go through?

**Comment by danswick** [comment]
Let's track over here instead: https://github.com/GSA-TTS/FAC/issues/2792
