### ISSUE TITLE
Run test suite in the CG dev space

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2948]
### Motivation
We are currently only able to run our test suite and use debugging capabilities in our local environment. The local environment is somewhat different from the environments we have in cloud.gov As a result, wesometimes find that what works well locally and passes our PR tests does not work as expected in the CG spaces.
This issue tries to alleviate the problem by ensuring that testing and debugging tools are available in the `dev` space and by setting up a GH action to triffer the test suite.

- CG Python buildpack installs python packages listed in requirements.txt. When deploying to the `dev` space (in deploy.sh), make sure requrements.txt includes the packages listed in dev-requirements.txt as well. 
- One way of doing this is to have a dev-requirements.txt and a prod-requirements.txt in our GH repo and to have deploy.sh pick the right one depending on the space. This approach will require changes to Makefile.
- Add a step test-dev-post-deploy in deploy-development.yml

### Tasks

```[tasklist]
- [ ] Make python packages available for testing and debugging in `dev`
- [ ] Implement a GH workflow to trigger the tests
```

**Comment by jadudm** [comment]
As indicated in slack, changing the composition of our deployed environments in order to do testing is not something I want to see us undertake.

We will be doing a postmortem on this failure, as it prevented us from deploying to `production` for a full work week while we chased and debugged the issue. At the heart of the issue was that a feature---involving *production infrastructure*---was poorly discussed, communicated, and reviewed before going into `dev` and `staging`. It could have disrupted service in `production`. A short question or conversation in Slack could have eliminated the breakage completely.

*Following the commit through to `staging`, per our existing PR process, would have also immediately caught this failure. Regressions were failing for a week.*

We will discuss the postmortem when we get back. *Better communication* and *better adherence to existing process* would have avoided the outage. Better post-deploy tests and expanded regressions (including regressions in `dev`) are a better choice than running tests internal to a production environment (for many reasons, including security). 

I'm closing this as not planned.
