### ISSUE TITLE
Figure out how to view database service performance

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2991]
It's not clear to me how to look at things like CPU/memory/disk load for the `fac-db` service, and this seems like something we need to know how to do in order to troubleshoot some performance problems the application is having.

This issue is for investigating how to access that data, and documenting the process.

**Comment by jadudm** [comment]
This is not something we can do; it is at the cgov level. Or, we can do a rudimentary performance eval in the dashboard, we can observe performance (to some degree) in NR, and we cannot observe DB performance at all, because only cgov has that data. They're working on it. 

Closing as not planned. Or, as already likely-as-done-as-it-will-be-for-now.
