### ISSUE TITLE
Failing to catch missing workbook named ranges in Findings workbook

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3216]
The findings workbook referenced in this ticket is missing some named ranges. 

I _think_ we already have some checks for this, but they might be per-workbook. In that case, we want to add some checks for the Findings workbook.

https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intakelib/checks/check_has_all_the_named_ranges.py

would seem to be the code that should have caught this, but didn't? 

Original HD ticket follows below

----------------------------------

### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1893

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/u/2/folders/1K4u5gMLoDIrTZJJYaJF_C7IOU3gNcSLT

### What happened?

This user's Federal Award Audit Findings workbook will not upload. I tested it in Dev, and the error message is blank.

**Comment by jadudm** [comment]
Running locally:

```
backend-web-1            | INFO No named range matches this error path: deque(['FindingsUniformGuidance', 'findings_uniform_gui
dance_entries', 0, 'findings', 'reference_number'])
backend-web-1            | INFO No named range matches this error path: deque(['FindingsUniformGuidance', 'findings_uniform_gui
dance_entries', 1, 'findings', 'reference_number'])
backend-web-1            | INFO No named range matches this error path: deque(['FindingsUniformGuidance', 'findings_uniform_gui
dance_entries', 2, 'findings', 'reference_number'])
backend-web-1            | WARNING FindingsUniformGuidance Excel upload failed validation: []\
```

The user managed to remove some named ranges, it looks like.

We need to update some validations to catch this.

**Comment by timoballard** [comment]
in these cases, our utility function appears to omit the requested named range from the result, logs it and moves on. Should the existence of the requested named ranges be invariant (in which case this seems like the place to throw some kind of error), or are there cases where this is expected behavior?

**Comment by danswick** [comment]
The issue here stems from the first three "Finding Reference Number" entries: `2001-001`. The workbook passes our initial checks because we don't have an explicit validator there. We check [_prior_ reference numbers](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intakelib/checks/check_finding_prior_references_pattern.py), but the current reference number only gets checked during our JSON schema validation, which happens as a last step. The JSON schema is looking for a reference number that begins with `201` (for example, `2019-005`) because we shouldn't be accepting any findings from before 2015 (I believe. @Carley-Jackson may have to verify). Here's the regular expression where that happens: https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/base/Base.libsonnet#L309. Unfortunately, our in-workbook validations are more permissive, allowing ref numbers to begin with `200`. We should probably update the in-workbook formula as well: https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/excel/libs/SheetValidations.libsonnet#L66. 

Possible next steps:
1. Add a check that mirrors the existing [prior reference numbers check](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intakelib/checks/check_finding_prior_references_pattern.py)
2. Update the in-workbook validations to check for a third number >0 [here](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/excel/libs/SheetValidations.libsonnet#L66). Possibly something like the following:
  ```
LEFT(FIRSTCELLREF, 3) > 0
  ```
