### ISSUE TITLE
Census migration: Handle ACE audits

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#3226]
When running the [2022 census migration](https://github.com/GSA-TTS/FAC/issues/3201), we saw ~200 errors of `'alternative-compliance-engagement' is not one of ['program-specific', 'single-audit']`. In the migration code, we currently [check for these and error/skip them specifically](https://github.com/GSA-TTS/FAC/blob/c2c2ba9fafdc852b080daacb05b6344d8fb9f3a0/backend/census_historical_migration/workbooklib/end_to_end_core.py#L202), but it’s never able to get to this point because of the validation error. In addition to other specialized ACE handling, we will need to add `alternative-compliance-engagement` to [AUDIT_TYPE_CODES](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/models/models.py#L294) and validator schemas.

**Comment by sambodeme** [comment]
We currently have 317 cases of migration failure related to audit_type matching `alternative-compliance-engagement`. 
As mentioned in the previous comment, these types of audit reports were supposed to fail [migration ](https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/end_to_end_core.py#L117) with the error tag `skip_ace_audit`.  However, because a [schema validation](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/base/Base.libsonnet#L172) check runs against the `general_information` section before it is saved in the database, the migration fails before it even reaches the logic designed to fail audit reports of `alternative-compliance-engagement` type. This [PR](https://github.com/GSA-TTS/FAC/pull/3231) will ensure that  `alternative-compliance-engagement` related failures are propely handled

**Comment by danswick** [comment]
This is done. ACE validations were correctly handled and skipped. They still exist in an "unmigrated" state for now and will need to be addressed separately.
