### ISSUE TITLE
Change "Submission date" on search summary page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3260]
On the single audit report summary page view on the search side, it currently says "Submission date" where it should say "FAC Acceptance date". 
![Screenshot 2024-01-23 at 11 01 51 AM](https://github.com/GSA-TTS/FAC/assets/123114420/361c0aa1-b108-4a0b-93c0-7c730e989430)
![Screenshot 2024-01-23 at 11 03 53 AM](https://github.com/GSA-TTS/FAC/assets/123114420/8a501725-d259-433e-b379-86f189b52f8a)

**Comment by jperson1** [comment]
This was in triage, but I wasn't paying attention and did it anyway. The branch is here, and can be PR'd when the issue is reviewed and moves to available:

https://github.com/GSA-TTS/FAC/tree/jp/summary-submission-date-to-acceptance-date

![image](https://github.com/GSA-TTS/FAC/assets/91098850/d36c9754-0a01-4913-a32f-d15191a50627)

**Comment by danswick** [comment]
Also: https://github.com/GSA-TTS/FAC/issues/3214

**Comment by lauraherring** [comment]
@jperson1 I think this looks good and we should go ahead and make a PR and merge it when possible. I'm going to move this from triage to in progress.
