### ISSUE TITLE
Load 2016-2022 into `staging`

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3336]
As part of moving disseminated records from preview to staging, the team was initially connecting to the database through an SSH tunnel using DBeaver. Then, they used the DBeaver tool to import the data backup file created in preview. The data load was significantly slow and often failed due to connection timeouts, the app instance being restarted, or duplicate key errors. To improve the process, the team opted to move the data files into an S3 bucket instead and perform the load by downloading the file directly to the staging instance and running the psql command. This approach helped mitigate all but one issue: the duplicate key error issue. The source of the duplicate key error issue remains unclear to the team at this time, as the files being loaded do not contain any primary key field (i.e., `id`) that could conflict with the existing records in the target tables. Also, the duplicate key error issue seems to appear only once (the first time a large data file is loaded into a table). After clearing the loaded records and retrying the load, subsequent attempts do not trigger the duplicate key error issue. It is being considered to split the large file into smaller chunks and surround each chunk with `BEGIN` and `COMMIT` to see if the issue persists. See cmd used below

**Comment by sambodeme** [comment]
As part of moving disseminated records from preview to staging, the team was initially connecting to the database through an SSH tunnel using DBeaver. Then, they used the DBeaver tool to import the data backup file created in preview. The data load was significantly slow and often failed due to connection timeouts, the app instance being restarted, or duplicate key errors. To improve the process, the team opted to move the data files into an S3 bucket instead and perform the load by downloading the file directly to the staging instance and running the psql command. This approach helped mitigate all but one issue: the duplicate key error issue. The source of the duplicate key error issue remains unclear to the team at this time, as the files being loaded do not contain any primary key field (i.e., `id`) that could conflict with the existing records in the target tables. Also, the duplicate key error issue seems to appear only once (the first time a large data file is loaded into a table). After clearing the loaded records and retrying the load, subsequent attempts do not trigger the duplicate key error issue. It is being considered to split the large file into smaller chunks and surround each chunk with `BEGIN` and `COMMIT` to see if the issue persists.

Below are the commands used to:
1. Install the S3 CLI (see .
```
# Install AWS cli
# [awscli.amazonaws.com](http://awscli.amazonaws.com/) needs to be added to the proxy allow list
curl -x $https_proxy -L "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip && rm awscliv2.zip
./aws/install -i ~/usr -b ~/bin

echo $https_proxy
# Copy this proxy endpoint somewhere as you will need to restore it back. Then
unset https_proxy
```
3. Set environment variables.
```
#Export Environment Variables
export S3CREDS="$(echo $VCAP_SERVICES|jq -r '.s3')"
export FACPRIVATE="$(echo $S3CREDS|jq '.[]|select(.name=="fac-private-s3")'|jq '.credentials')"
export AWS_ACCESS_KEY_ID="$(echo "$FACPRIVATE"|jq -r '.access_key_id')"
export AWS_SECRET_ACCESS_KEY="$(echo "$FACPRIVATE"|jq -r '.secret_access_key')"
export BUCKET_NAME="$(echo "$FACPRIVATE"|jq -r '.bucket')"
export AWS_DEFAULT_REGION='us-gov-west-1'

export db_name=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.name')
export username=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.username')
export host=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.host')
export port=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.port')

export PATH=/home/vcap/deps/0/apt/usr/lib/postgresql/15/bin:$PATH
export PATH=/home/vcap/app/bin:$PATH
```
5. List the contents of the buckets.
```
aws s3 ls s3://${BUCKET_NAME}/migration_data_load/
```
7. Copy a data file from the bucket.
```
aws s3 cp s3://${BUCKET_NAME}/migration_data_load/cgawsbrokerprodbw9xqb9tln0436y_dissemination_federalaward_202401301426_dissemination_federalaward.sql   dissemination_federalaward.sql
```
9. Load data into a table.
```
#This cmd we ask you for a password
psql -h $host -p $port -U $username -d $db_name -f dissemination_federalaward.sql
```
