### ISSUE TITLE
Enable removal of editors, certifiers from SF-SAC records

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3409]
## What problems are we trying to solve?

Currently, it is possible to:

1. Add editors to an audit submission.
2. Change certifying officials.
3. Change editors.

It is not possible to *remove* editors. This is a problem.

## What can we do today?

* We will add a feature granting users with the Audit Editor role the ability to remove that role from others.
* We will not allow users with the Audit Editor role to remove themselves from that role. (In practice, this will mean that they must add another user with that role, and that user must then remove them.)
* We will not add the ability to remove Certifying Official roles without supplying new users for those roles; we will evaluate how many requests we get that are for exactly this operation.
* We will not add any out-of-band processes for adding or removing users from submissions.

## Context and further reading

We have discussed [via the ADR process](https://github.com/GSA-TTS/FAC/issues/3881). 

*Link to ADR when it is complete.*

```[tasklist]
### Requirements
- [x] Add a Remove link to the current access management table
- [x] Add a Remove page for deleting an Auditor Access role
- [x] Create a method for audit.views.manage_submission_access.ChangeOrAddRoleView to support deletion
- [x] Ensure that the new method does not allow deletion when the email in the Access object being deleted matches the email of the current user
- [ ] https://github.com/GSA-TTS/FAC/issues/4404
- [ ] https://github.com/GSA-TTS/FAC/issues/4403
- [ ] Track how many requests we get for removing Certifying Official roles without supplying a replacement
- [x] Potentially add documentation suggesting that larger organizations always add at least two of their staff in the Audit Editor role, to ensure that they do not get stuck without access to an audit if one of their staff members leaves
```

**Comment by jadudm** [comment]
The "verify completed audits" story is supported in part by tickets like this:

https://fac-gov.zendesk.com/agent/tickets/2356

**Comment by James-Paul-Mason** [comment]
### Main User Management Page

The table below lists the individuals with access to this single audit submission.

There must only be one Auditee Certifying Official and one Auditor Certifying Official. These users must have different email addresses. Any substitution for these roles will remove the prior user.

To change an individual's role, click the “Edit” link in the table. At this time, you can only change the certifying officials, and this can only be done by an Audit Editor.

It's recommended that larger organizations always add at least two of their staff in the Audit Editor role. This ensures that an audit does not become inaccessible due to the departure of a staff member.

**Comment by James-Paul-Mason** [comment]
### Remove access page

Remove Editor
You do not have permission to remove audit access for this editor:
Name: XXXXX
Email: XXXXXX @ gsa.gov

Audit Editors cannot remove their own access. This helps to ensure that an audit remains accessible to an organization.
