### ISSUE TITLE
`dissemination.summary_reports` fields should be generated, not hardcoded

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3549]
The fact that they're not is one of the reasons that `auditor_certify_name`, for example, is absent from the summary report fields.

**Comment by phildominguez-gsa** [comment]
Did some digging on this. [The fields](https://github.com/GSA-TTS/FAC/blob/v1.20240925/backend/dissemination/summary_reports.py#L112) are currently hardcoded because they are maintaining a specific order we want to keep in order to match the workbooks that users upload. Generating these fields off the models would mess up this ordering. Possibly we can manually list the fields we want ordered and then auto-generate the remainder, but fixing the missing fields and being vigilant about updates might be the best way to go.

**Comment by phildominguez-gsa** [comment]
I went through all the dissemination models/fields and fixed the only two that were missing, auditor_certify_title and auditor_cerity_name. Thoughts on closing this @danswick, considering my previous comment?

**Comment by danswick** [comment]
We plan to revisit the generated workbooks in much more detail later on, so it's not worth pursuing this further now.
