### ISSUE TITLE
Address historical audits with invalid reference numbers

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#3698]
- Error message: `Reference numbers must be formatted YYYY-NNN`
- Example: 227682, 2016
  - 231373, 151697, 181006 have shortened numbers, but many have years pre-2010, which [we don’t allow](https://github.com/GSA-TTS/FAC/blob/75c994bbce29757b8ed4431ea21555a63a2d951a/backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json#L121)
- Explanation: TBD
- Proposed solution: TBD

**Comment by sambodeme** [comment]
This ticket is resolved by #3753. For context, some historical reports failed the first round of migration due to an invalid reference number format. Upon investigation, it was discovered that the failures were due to the validation schema of the reference numbers, which only allowed the format YYYY-###. Here, YYYY must be a year greater than 2010, and ### represents any three digits. The error details revealed that the failing reports had reference numbers with years prior to 2010, such as 2006-010. The team-approved solution is to allow any year in the reference number.
