### ISSUE TITLE
Implement MVP file scanning functionality in the periodic scanner application

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3761]
Using the [existing scan-at-rest Django command as a starting point](https://github.com/GSA-TTS/fac-periodic-scanner/blob/main/scan_bucket_files_for_viruses.py), implement the MVP periodic scanning functionality as described in the parent issue:

> The application should consume a simple configuration at startup that provides the necessary information about the S3 bucket and ClamAV service. From there, the application will continuously traverse the targeted S3 bucket, performing a ClamAV scan on each file it finds.
> 
> Future iterations will include writing last scan timestamps for each file to the FAC database, which will allow the scanner to pick up where it left off in the event of an application crash or restart, but this feature is not strictly necessary and should therefore not be part of the MVP.
```[tasklist]
### We're done when
- [ ] Target S3 bucket configuration is read at startup from VCAP_SERVICES (or a local development analog)
- [ ] ClamAV endpoint configuration is read at startup from an environment variable
- [ ] After successful startup, the application traverses all files in the target S3 bucket, scanning each with ClamAV and logging the scan results
- [ ] When the application completes a full traversal of the S3 bucket, it starts over from the beginning
- [ ] Application logs are shipped to New Relic
```

**Comment by asteel-gsa** [comment]
As a reminder, due to the nature of
```terraform
data "external" "scannerzip" {
  program     = ["/bin/sh", "prepare-scanner.sh"]
  working_dir = path.module
  query = {
    gitref = var.gitref
  }
}
```
running in `preview` at this time, any changes to [scanner repo](https://github.com/GSA-TTS/fac-periodic-scanner) will require a `cf delete fac-file-scanner -r -f` to ensure the app and associated routes are deleted, and then a [redeploy](https://github.com/GSA-TTS/FAC/actions/workflows/deploy-preview.yml) with `branch` == `scanning-app`, to pick up new code changes. This is a known bug at this time, and something I would like to fix
