### ISSUE TITLE
Figure out why GitHub action to deploy SAM.gov API key didn't work

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#384]
### Background

#376 revealed that the GitHub deployment action didn't do exactly what we expected. Figure out why that is.

### Acceptance Criteria (We'll know we're done when...)

- [ ] The deployment action does what we expected, OR
- [ ] We have an alternative mechanism for changing the API keys.

**Comment by geekygirlsarah** [comment]
Thought for Future Sarah: Try seeing if the action in `.github/workflows/deploy.yml` (the 18f/cf-...something) has the right push arguments and/or don't need something like `"${SAM_API_KEY}"` in curly brackets when quoted.

**Comment by geekygirlsarah** [comment]
My learnings:

Presently the `.github/workflows/deploy.yml` file tries to send the SamGov key via `cf push --vars`, but according to [the docs](https://cli.cloudfoundry.org/en-US/v6/push.html), looks like `--vars` is to swap variables in the manifest file, not set environment variables via CLI.  (That's what `cf set-env` is for, see [docs](https://cli.cloudfoundry.org/en-US/v6/set-env.html).)

"Easy" fix:  Use [18f/cg-deploy-action](https://github.com/18F/cg-deploy-action) to run `cf set-env` instead using the example they provide.

"Better" fix: Use Cloud Foundry's [User-Provided Service Instances](https://docs.cloudfoundry.org/devguide/services/user-provided.html) to set up ways to deliver service credentials to the app. It doesn't look hard, but the testing to do it right might take an afternoon by reading this over.

**Comment by geekygirlsarah** [comment]
Update: 
- [X] Started down the "better" fix with making a UPSI. It has the new key in it
- [X] The UPSI is bound to the `gsa-fac-dev` instance and it can "see" the SamGov key
- [X] Verified it comes through as a different environment variable (`VCAP_SERVICES` which is a JSON blob, which has `key-service->credentials->SAM_API_KEY`)
- [ ] Going to update the app so it can use that key instead of the insecure `SAM_API_KEY` environment variable
- [ ] Going to update the GitHub Action so it can pass through the key through the UPSI instead

**Comment by geekygirlsarah** [comment]
Latest status for Monday Sarah: Code works, it can read the key just fine from the UPSI. GitHub Actions is not taking its secret and adding it to the UPSI deploy part (it just comes through as "$SAM_API_KEY"). Need to fix that, possibly with `${SAM_API_KEY}" ?

**Comment by jadudm** [comment]
This was done a long time ago, and not closed? Or, it was closed, and re-opened? 

Closing, again.
