### ISSUE TITLE
[HD]: dev secrets Document Mentioned in development.md is not publicly available

### ISSUE THREAD

**Issue by joffemd** [GSA-TTS/FAC#3974]
### Zendesk link

n.a.

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [X] other

### What browser did the user report as using?

Chrome

### What happened?

development.md includes the following:  (Recommended) If you wish to use the shared Login.gov sandbox client application and credentials, you can obtain a valid DJANGO_SECRET_LOGIN_KEY from our shared [dev secrets document](https://docs.google.com/spreadsheets/d/1byrBp16jufbiEY_GP5MyR0Uqf6WvB_5tubSXN_mYyJY/edit#gid=0)

But the link to the dev secrets document is not available. I get a Google prompt to request access.

**Comment by jadudm** [comment]
Hi Mark,

As the documentation states:

```
If you wish to use your own Login.gov sandbox client application, follow [Login.gov's documentation for setting up a test application](https://developers.login.gov/testing/). Once completed, open settings.py and set OIDC_PROVIDERS.login.gov.client_registration.client_id so that it matches the issuer string for your newly-created client application. NOTE: changes to the client_id should not be checked into version control!
```

For local experimentation, I recommend [disabling authentication](https://github.com/GSA-TTS/FAC/blob/main/docs/development.md#disable_auth) instead of trying to do the above. It would be difficult for you to setup a Login.gov sandbox and attempt to recreate the FAC in its entirety. Disabling authentication should allow you to proceed with your local experimentation.
