### ISSUE TITLE
FAC - Bug: PDF with minimal text passed through

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3999]
### Describe the bug

https://app.fac.gov/dissemination/summary/2023-06-GSAFAC-0000039486

This PDF looks to be mostly a scan. Our PDF validations were scaled back to speed them up, and we believed we had a good threshold. This PDF should not have made it through.

We need to look at this PDF, look at our validations, and proceed appropriately based on what we find.

### Steps to reproduce the bug

Cannot copy-paste from the PDF; no text seems to be accessible.

### Expected Behavior

PDF should have easily copy-pastable text. (I have not probed this deeply at this time.)

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by danswick** [comment]
We could possibly take a random sampling approach, but I think we'd need to decide if that would be worth the effort. We don't currently do anything with the text in these PDFs, but we may need to provide our partners and the public with some level of assurance that the entire PDF is actually constructed out of real text. 

Maybe a good first step here would be to test a sample-based approach (every tenth page or something) to see how much overhead it adds.

**Comment by phildominguez-gsa** [comment]
Just to note: I think the "scaling back" Matt is referencing is [this fix](https://github.com/GSA-TTS/FAC/pull/3057), which was really just stopping us from writing the entire pdf into a single string, and instead tries to detect any text at all. Since then, we've made it a bit picker by [setting a 6000 character limit](https://github.com/GSA-TTS/FAC/pull/3238). I'll keep an eye out for problematic processing times while I'm testing, though!

**Comment by phildominguez-gsa** [comment]
I've collected some data on 500 pdfs we have in prod to see what else we can use to catch bad pdfs besides character counts. I think determining the percentage of pages with readable text could be useful. With Matt's example, the pdf is large and has well over the current 6000 character requirement, but the parser says only 11% of the pages have anything readable. In the 500 I tested, only 6 had a percentage under 90%:
<img width="980" alt="image" src="https://github.com/user-attachments/assets/b5d8b7a1-5aa8-436c-b062-014040bd8fac">

The top 3 would already have been caught by the character limit. The other 3 have some pages that could be tougher to read because of scans, but the Mac pdf reader can highlight/copy just about everything, so it may just depend on the reader used. It makes me think being conservative with the percentage threshold would be the way to go.
[2022-12-GSAFAC-0000000880.pdf](https://app.fac.gov/dissemination/summary/2022-12-GSAFAC-0000000880)
[2022-06-GSAFAC-0000000684.pdf](https://app.fac.gov/dissemination/summary/2022-06-GSAFAC-0000000684)
[2023-06-GSAFAC-0000001606.pdf](https://app.fac.gov/dissemination/summary/2023-06-GSAFAC-0000001606)
