### ISSUE TITLE
Historical audits missing SACs (PDF only)

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4043]
In the Census historic data in Preview, there are 212 audits that do not have any awards.  Review Census tables and analyze.

**Comment by gsa-suk** [comment]
audit_year, dbkey details of these audits are here - https://drive.google.com/drive/folders/1TKoEMcOsUkS7NnGTq6JSmeDGWlFmN6eK

**Comment by danswick** [comment]
We've discussed these PDF-only records a few times and it's not clear that there's a viable path forward for them. I see a couple of likely scenarios (though there are likely lots of others I'm not thinking of):

1. They're duplicates left over from resubmissions or similar. If that's the case, we don't need them.
2. They're somehow associated with reports that were never completed and submitted, in which case there's nothing to do because there just wouldn't be a record to associate them with.
3. The SAC records were somehow lost in the Census data. If that's the case, the only path forward would be to construct some minimal version of the SAC around them, which doesn't strike me as a useful or appropriate exercise. 

I'm going to close this issue for now. If we learn anything new, we can always re-open the issue and find the associated records that @gsa-suk created.
