### ISSUE TITLE
Create production deployment workflow

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#420]
### Background
We currently only have a Github Action workflow for deploying to the dev cloud.gov space. We'll need to either create a separate workflow for production, or we'll need to modify the current one to be flexible with respect to deployment environments.

We also need to change to the OROS organization and stop using the 10x org and space we’re currently in.

We should switch to a gitflow-based branching workflow when we move to the new space, since we’ll need that when the app is more mature, and also before the vendor team starts.

### Acceptance Criteria (We'll know we're done when...)

- [x]   When the dev deployment workflow is triggered (on new commits to `main` branch), the app is deployed to the dev cloud.gov space.
- [x]   We’ve defined the gitflow-like approach to handling `main` and `dev` branches and feature development work and hotfixes.
- [x]   We’ve moved out of the 10x cloud.gov environment.
- [x]   When the production deployment workflow is triggered (TBD), the app is deployed to the production cloud.gov space.

**Comment by tadhg-ohiggins** [comment]
From a discussion I had with @geekygirlsarah at dev huddle on 2022-10-05:

*   We need to know what the names of the cloud.gov (and cloud.gov Pages) organizations and spaces are in order to use them. We’ve asked Matt J for that information in Slack.
*   We will need to switch our dev space to whatever the new official FAC one is once we learn those details. This will require changing URLs for our preview instance and some other tweaks to our CI/CD pipeline, which hopefully will just be a question of swapping out URLs.
*   We’re not being forced out of our current cloud.gov space/org, but we should switch to the long-term one as soon as possible, before billing/ATO/other forces require us to do so at short notice.

**Comment by mogul** [comment]
I'm in the process of [getting the new `gsa-oros-fac` org set up](https://gsa-tts.slack.com/archives/C0DF6LAMQ/p1667422964574869?thread_ts=1662998403.399659&cid=C0DF6LAMQ).

**Comment by tadhg-ohiggins** [comment]
I removed the folks on our team from the `gsa-10x-prototyping` cloud.gov org.

**Comment by LindsayYoung** [comment]
Let's close this epic when #712 is finished
