### ISSUE TITLE
#4543 FAC - Bug: Missing DCF?

### ISSUE THREAD

**Issue by RanyeM** [GSA-TTS/FAC#4234]
### Describe the bug

Bug shared via helpdesk at https://fac-gov.zendesk.com/agent/tickets/4543

"I cannot seem to be able to access the DCF for the following. Please advise.

Single audit summary
Oregon Primary Care Association

UEI: KAM4HNCW7XC5

Report ID: 2023-03-GSAFAC-0000000334

FAC acceptance date: Dec. 4, 2023

Fiscal Year: April 1, 2022 to March 31, 2023"

### Steps to reproduce the bug

Search using the UEI on the fac.gov site 
Click on View 
Try to download the SF-SAC  by clicking on the download button 

### Expected Behavior

Should be able to download the SF-SAC but it is greyed out 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by phildominguez-gsa** [comment]
This issue occurs when a submission has zero federal awards (Slack discussion [here](https://gsa-tts.slack.com/archives/C06FLEJURMG/p1724853943112299)). This is because the button becomes disabled if no entries can be found in [DisseminationCombined](https://github.com/GSA-TTS/FAC/blob/deb03cb1fb7238672af910df4993e6468a51f989/backend/dissemination/models.py#L622C7-L622C28). This materialized view is refreshed nightly, so the idea for this check was to prevent users from downloading empty SF-SACs before they get a chance to be populated. @danswick @jadudm Maybe we could enable the button if an entry exists in DisseminationCombined OR if it's been > 24h since their submission time?

**Comment by danswick** [comment]
From some prior notes: 

> We probably need to treat these like the “[five stuck SACs](https://github.com/GSA-TTS/FAC/issues/3764)” from days of yore: find all cases of 0 federal awards, reach out to everyone to let them know their reports are incorrect, present options.

Before reaching out to these folks, we should check to see if these UEIs have submitted again.

**Comment by danswick** [comment]
This entity has since submitted successfully: https://app.fac.gov/dissemination/summary/2024-03-GSAFAC-0000055776
