### ISSUE TITLE
Update UI copy to support removal of contacts

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4403]
Follow-on work from https://github.com/GSA-TTS/FAC/issues/3409. This ticket tracks application copy updates, specifically.

**Comment by James-Paul-Mason** [comment]
### Main user management page
The table below lists the individuals with access to this single audit submission.

There must only be one Auditee Certifying Official and one Auditor Certifying Official. These users must have different email addresses. Any substitution for these roles will remove the prior user.

To change an individual's role, click the “Edit” link in the table. At this time, you can only change the certifying officials, and this can only be done by an Audit Editor.

It's recommended that larger organizations always add at least two of their staff in the Audit Editor role. This ensures that an audit does not become inaccessible due to the departure of a staff member.

**Comment by James-Paul-Mason** [comment]
### Remove access page
Remove Editor
You do not have permission to remove audit access for this editor:
Name: XXXXX
Email: XXXXXX @ gsa.gov

Audit Editors cannot remove their own access. This helps to ensure that an audit remains accessible to an organization.
