### ISSUE TITLE
Identify source for cluster information

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#520]
## Background
The cluster and/or state cluster entries in federal award entries need to be validated against a list of clusters. We need to figure out what the source of that information is, how to get it automatically, and how to insert it into our schema(s), first as a static list and later dynamically to accommodate changes in the source information.

## Acceptance Criteria

- [ ] We know where the cluster information comes from
- [ ] We know how to get it automatically

**Comment by pkigongo** [comment]
Q: Who needs to identify the source for cluster info? 
Q: How important is validating this cluster info?

**Comment by melchoyce** [comment]
From our Census sync:

**Q: Who needs to identify the source for cluster info?**
- Listed in a compliance supplement that’s issued every year. There’s an appendix that lists clusters. 
- How often do new clusters get added?
  - New compliance supplement every year.
- How do you get notified when it comes out?
  - Via email from someone @ OMB

**Q: How important is validating this cluster info?**
- Is it necessary to ensure that in that cell, that only a cluster in the compliance document can be entered? 
- In the GUI, there's a dropdown list for Clusters.
- We should be providing a dropdown and prompts from the user; those prompts should come from compliance doc. How difficult for you to give us that list?
  - Awards_Uniform_Guidance_891917_1_Unprotected.xlsx 
- A new cluster might form in between publications of the compliance document, which is why we have to allow for entry of clusters we don’t know about.
- Compliance doc comes out about once per year. Latest: https://www.whitehouse.gov/wp-content/uploads/2022/05/2022-Compliance-Supplement_PDF_Rev_05.11.22.pdf
- Others are listed here: https://facweb.census.gov/Resources.aspx

**Comment by melchoyce** [comment]
Is there anything additional design can help with here?
