### ISSUE TITLE
Data Migration Epic

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#723]
# ETL
Extract, transform, load

User story:
In order for people to find historical data on the new website, we need to import data from the census system.

```[tasklist]
### First steps
- [x] #742
- [x] #743
- [x] #744
- [x] #745
- [x] #746
- [ ] #747
- [ ] #913
- [ ] #1010
- [ ] #890
- [ ] #748
- [ ] #749
```

```[tasklist]
### Once we get all the data
- [ ] #750
- [ ] #751
- [ ] https://github.com/GSA-TTS/FAC/issues/1047
```

Next steps (I suggest a separate Dissemination Epic for tracking):
- Create a way for identifying who should have access to the private PDFs.
- Create a way to serve PDFs to authenticated users.
- Create a workflow that takes published data from the new form into the data distro
- Create a workflow that takes published data from the distro and sends it to the form to generate a base for amendments.

At this point, he dissemination site will be ready to build

**Comment by pkigongo** [comment]
Also to do: Create a crosswalk that's available to data users for their change management and point their fields to new GSA instance

**Comment by JeanMarie-TTS** [comment]
Pasting a note from Virginia: JeanMarie to make recommendations on how far back data migration should go, whether some data should be archived instead of migrated, etc. Note: at some point, we should raise the issue of getting a records retention decision for audits, but this is likely to take some time and won’t happen prior to September 2023. In the meantime, we need a plan for all data.

**Comment by LindsayYoung** [comment]
I am doing some research that will become a rough plan and some tickets. In the meantime, I am taking notes for myself here: https://docs.google.com/document/d/1j4HlhaeSB-27e_d8gxsYSDB7WFy7Cc8h_HG_RmbuPfo/edit#heading=h.kx4hs7t0lh3h
